site_name: Probely Help and Documentation
site_description: 'Documentation for using Probely'
site_author: 'Martim :)'
site_url: 'https://martimvalente.github.io/support-docs/'

copyright: |
  &copy; Probely 2021

docs_dir: docs/

nav:
  
  - Overview:  
    - Get Started: index.md
    - What is Probely: what-is-probely.md
    - SMB and Enterprise: editions.md
    - Types of Plans: types-of-plans.md
  - Adding a Target:  
    - Types of Targets: types-of-targets.md
    - Adding a Web Target: publishing-your-site.md
    - Adding an API Target: publishing-your-site.md  
    - Verifying a Target: index1.md
    - Types of Targets: types-of-targets.mdtt
    - Publishing your site: publishing-your-site.md
  - Target Configuration:
    - Installation: index1.md
    - Types of Targets: types-of-targets.md
    - Publishing your site: publishing-your-site.md
  - Integrations:  
    - Installation: index1.md
    - Types of Targets: types-of-targets.md
    - Publishing your site: publishing-your-site.md
  - Helpful Resources:  
    - Installation: index1.md
    - Types of Targets: types-of-targets.md
    - Publishing your site: publishing-your-site.md


theme:

  name: 'material'
  
  custom_dir: 'theme'
  
  favicon: 'assets/img/favicon.png'

  logo: 'assets/img/logo.png'
    
  
  font:
    text: 'sans-serif'
    code: 'Roboto Mono'
  
  language: 'en'

  features:
  # Header
  #
  #- header.autohide # Hide header when user scrolls past a specific point.
  
  # Navigation:
  #
  #- navigation.expand      # Expand all collapsible sections.
  #- navigation.instant     # Instant loading pages.
  #- navigation.indexes     # Attach pages directly to Sections.*
  #- navigation.sections    # Render top sections as groups.
  - navigation.tabs         # Render top sections as tabs at the top.
  - navigation.tabs.sticky # Always show tabs.*
  #- navigation.top         # Adds a "Back to top" button in the corner.
  #- navigation.tracking    # Updates the url with highlighted section anchor.*
  
  # Search
  #
  - search.highlight # Search will highlight the searched word(s) on the page.*
  #- search.share     # Adds an option to share a search query link.*
  - search.suggest   # Search will suggest the likeliest completion for a word.*

  icon:
    logo: 'material/library'
    repo: 'material/library'
  
extra_css:
  - assets/css/extra.css
#extra_javascript:

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/probely
    - icon: fontawesome/brands/linkedin
      link: https://twitter.com/squidfunk
    - icon: fontawesome/brands/github
      link: https://github.com/Probely/

markdown_extensions:
  - markdown.extensions.admonition:
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: true
  #- pymdownx.arithmex:
  #- pymdownx.b64:
  #- pymdownx.betterem:
  #- pymdownx.caret:
  #- pymdownx.critic:
  #- pymdownx.details:
  #- pymdownx.emoji:
  #- pymdownx.escapeall:
  #- pymdownx.extra:
  #- pymdownx.extrarawhtml:
  #- pymdownx.highlight:
  #- pymdownx.inlinehilite:
  #- pymdownx.keys:
  #- pymdownx.magiclink:
  #- pymdownx.mark:
  #- pymdownx.pathconverter:
  #- pymdownx.progressbar:
  #- pymdownx.smartsymbols:
  #- pymdownx.snippets:
  #- pymdownx.striphtml:
  #- pymdownx.superfences:
  #- pymdownx.tabbed:
  #- pymdownx.tasklist:
  #- pymdownx.tilde: